### ISSUE TITLE
带有系数的公式

### ISSUE THREAD

**Issue by trytodupe** [HLXY-420/UncertaintyCalc#1]
当输入公式带有系数时，不确定度传递公式会有误

Input1:

$$ y=2x $$

Output1:

$$ \frac{\mathrm{\Delta_{y}}}{y}=\sqrt{\mathrm{\Delta_{x}^2}\frac{1}{x}^2} $$

Input2:

$$ y=\frac12\left(a+b\right) $$

Output2:

$$ \frac{\mathrm{\Delta_{y}}}{y}=\sqrt{\mathrm{\Delta_{a}}^2\frac{1}{a+b}^2+\mathrm{\Delta_{b}}^2\frac{1}{a+b}^2} $$

Input3:

$$ y=\frac{a}{2}+\frac{b}{2} $$

Output3:

$$ \frac{\mathrm{\Delta_{y}}}{y}=\sqrt{\frac{\frac{\mathrm{\Delta_{a}}^2}{2}}{(0.5a+0.5b)^2}+\frac{\frac{\mathrm{\Delta_{b}}^2}{2}}{(0.5a+0.5b)^2}} $$

Input4:

$$ y=2\left(a+b\right) $$

Output4:

$$ \frac{\mathrm{\Delta_{y}}}{y}=\sqrt{\mathrm{\Delta_{a}}^2\frac{1}{a+b}^2+\mathrm{\Delta_{b}}^2\frac{1}{a+b}^2} $$

Input5:

$$ y=2a+2b $$

Output5:

$$ \frac{\mathrm{\Delta_{y}}}{y}=\sqrt{\frac{(2\mathrm{\Delta_{a}})^2}{(2a+2b)^2}+\frac{(2\mathrm{\Delta_{b}})^2}{(2a+2b)^2}} $$

**Comment by HLXY-420** [comment]
这些公式是正确的，只是因为技术问题，目前只能把所有不确定度传递公式显示为乘除法的形式，只需把公因数提出来再两边乘以它们的倒数就可以转化成一般的加减法对应的形式了。
以Input1为例：
$$ y=x $$
对应的不确定度公式：
$$ \frac{\mathrm{\Delta_{y}}}{y}=\sqrt{\mathrm{\Delta_{x}}^2\frac{1}{x}^2} $$
提取公因式：
$$ \frac{\mathrm{\Delta_{y}}}{y}=\frac{1}{x}\sqrt{\mathrm{\Delta_{x}}^2} $$
根据输入替换y的内容：
$$ \frac{\mathrm{\Delta_{y}}}{x}=\frac{1}{x}\mathrm{\Delta_{x}} $$
两边同除 $1/x$ ：
$$ \mathrm{\Delta_x} = \mathrm{\Delta_{x}} $$

**Comment by HLXY-420** [comment]
确实是个问题，之前懒了没写加减法公式的判断，看来用的运算内核在Ln计算上的问题还很多，在修了。

**Comment by HLXY-420** [comment]
[在最新的提交中已增加对加减法公式的处理：[7ab2eda](https://github.com/HLXY-420/UncertaintyCalc/commit/7ab2eda84f5f0e130f50266b3a69f45e7bab237c) ，现在网站应该已经同步更新了。
